import os
import requests

def analyze_source_code(file_path, model_name="qwen2.5-coder:7b"):
    """
    Reads a local source file and leverages a local LLM instance 
    to perform static application security testing (SAST).
    """
    # Verify file existence before initiating the pipeline
    if not os.path.exists(file_path):
        return f"Error: Target file '{file_path}' not found in the working directory."

    print(f"[*] Reading source file: {file_path}")
    with open(file_path, "r", encoding="utf-8") as file:
        source_code = file.read()

    # Define the local inference server endpoint provided by Ollama
    local_api_url = "http://localhost:11434/api/generate"

    # Engineering a precise prompt to force the model into a DevSecOps role
    system_prompt = (
        "You are an expert DevSecOps Engineer and C++ Security Auditor. "
        "Analyze the following code for critical security vulnerabilities, "
        "specifically focusing on buffer overflows, memory corruption, or unsafe functions. "
        "Provide a concise summary of the flaw, its security risk, and the secure refactored code."
    )

    full_prompt = f"{system_prompt}\n\n--- SOURCE CODE START ---\n{source_code}\n--- SOURCE CODE END ---"

    # Constructing the structural payload (No API keys needed for local environments)
    payload = {
        "model": model_name,
        "prompt": full_prompt,
        "stream": False  # Block streaming to fetch the complete payload response at once
    }

    print(f"[*] Initiating local inference via {model_name}...")
    try:
        response = requests.post(local_api_url, json=payload, timeout=60)
        
        if response.status_code == 200:
            # Extracting the standard response string from the local engine
            return response.json().get("response", "No response payload received.")
        else:
            return f"Error: Local server returned status code {response.status_code} - {response.text}"

    except requests.exceptions.ConnectionError:
        return (
            "Critical Error: Failed to connect to the local inference engine. "
            "Ensure that Ollama service is active (`ollama serve`) and the model is pulled."
        )

if __name__ == "__main__":
    print("=== Local AI Architecture Laboratory: Milestone 1 ===")

    target_file = input("Type Path")
    # target_file = "/home/can/zero-to-ai-architect/target_code.cpp"
    
    # Fire the scanning pipeline
    security_report = analyze_source_code(target_file)
    
    print("\n[+] Security Audit Report Generated by Local LLM:\n")
    print(security_report)